#pragma once

// Browse-Antwort für die Sonos-Favoriten (ObjectID FV:2).
//
// Nachgebaut nach dem bekannten Aufbau (Result = DIDL-Lite einfach kodiert, darin r:resMD
// nochmals kodiert) – eine echte Aufzeichnung folgt mit „sonos_probe.py … --save … favorites“.
// Enthält je einen Favoriten pro Art:
//   TuneIn-Sender, Spotify-Playlist, Spotify-Album, Spotify-Einzeltitel, Sonos-Playlist,
//   Sonos Radio, eine Verknüpfung ohne Adresse.
// Tokens und IDs sind Platzhalter.

namespace fixtures {

static const char* kFavoritesBrowse =
    R"~(<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/so)~"
    R"~(ap/encoding/"><s:Body><u:BrowseResponse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><Result>&lt;)~"
    R"~(DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata)~"
    R"~(-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp)~"
    R"~(-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;FV:2/10&quot; parentID=&quot;FV:2&quot; restricted=&qu)~"
    R"~(ot;false&quot;&gt;&lt;dc:title&gt;Deutschlandfunk&lt;/dc:title&gt;&lt;upnp:class&gt;object.itemobject.item.son)~"
    R"~(os-favorite&lt;/upnp:class&gt;&lt;r:ordinal&gt;0&lt;/r:ordinal&gt;&lt;res protocolInfo=&quot;x:*:*:*&quot;&gt;)~"
    R"~(x-sonosapi-stream:s42828?sid=254&amp;amp;flags=8224&amp;amp;sn=0&lt;/res&gt;&lt;upnp:albumArtURI&gt;https://cd)~"
    R"~(n-profiles.tunein.com/s42828/images/logoq.png&lt;/upnp:albumArtURI&gt;&lt;r:type&gt;instantPlay&lt;/r:type&gt;)~"
    R"~(&lt;r:description&gt;TuneIn&lt;/r:description&gt;&lt;r:resMD&gt;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://pu)~"
    R"~(rl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns)~"
    R"~(:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metad)~"
    R"~(ata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;F00092020s42828&amp;quot; parentID=&amp;quot;-1&)~"
    R"~(amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;dc:title&amp;gt;Deutschlandfunk&amp;lt;/dc:title&)~"
    R"~(amp;gt;&amp;lt;upnp:class&amp;gt;object.item.audioItem.audioBroadcast&amp;lt;/upnp:class&amp;gt;&amp;lt;desc i)~"
    R"~(d=&amp;quot;cdudn&amp;quot; nameSpace=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;)~"
    R"~(SA_RINCON65031_&amp;lt;/desc&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&lt;/r:resMD&gt;&lt;/item&g)~"
    R"~(t;&lt;item id=&quot;FV:2/11&quot; parentID=&quot;FV:2&quot; restricted=&quot;false&quot;&gt;&lt;dc:title&gt;To)~"
    R"~(day&amp;apos;s Top Hits&lt;/dc:title&gt;&lt;upnp:class&gt;object.itemobject.item.sonos-favorite&lt;/upnp:class)~"
    R"~(&gt;&lt;r:ordinal&gt;1&lt;/r:ordinal&gt;&lt;res protocolInfo=&quot;x:*:*:*&quot;&gt;x-rincon-cpcontainer:10062)~"
    R"~(06cspotify%3aplaylist%3a37i9dQZF1DXcBWIGoYBM5M?sid=9&amp;amp;flags=8300&amp;amp;sn=2&lt;/res&gt;&lt;upnp:album)~"
    R"~(ArtURI&gt;https://i.scdn.co/image/ab67706f00000002aaaa&lt;/upnp:albumArtURI&gt;&lt;r:type&gt;instantPlay&lt;/r)~"
    R"~(:type&gt;&lt;r:description&gt;Spotify-Playlist&lt;/r:description&gt;&lt;r:resMD&gt;&amp;lt;DIDL-Lite xmlns:dc=)~"
    R"~(&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/up)~"
    R"~(np/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:sch)~"
    R"~(emas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;1006206cspotify%3aplaylist%3a)~"
    R"~(37i9dQZF1DXcBWIGoYBM5M&amp;quot; parentID=&amp;quot;-1&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&a)~"
    R"~(mp;lt;dc:title&amp;gt;Today&amp;amp;apos;s Top Hits&amp;lt;/dc:title&amp;gt;&amp;lt;upnp:class&amp;gt;object.c)~"
    R"~(ontainer.playlistContainer&amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&amp;quot;cdudn&amp;quot; nameSpace=&amp;)~"
    R"~(quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;SA_RINCON2311_X_#Svc2311-0-Token&amp;lt;/de)~"
    R"~(sc&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&lt;/r:resMD&gt;&lt;/item&gt;&lt;item id=&quot;FV:2/1)~"
    R"~(2&quot; parentID=&quot;FV:2&quot; restricted=&quot;false&quot;&gt;&lt;dc:title&gt;Stank Face&lt;/dc:title&gt;&)~"
    R"~(lt;upnp:class&gt;object.itemobject.item.sonos-favorite&lt;/upnp:class&gt;&lt;r:ordinal&gt;2&lt;/r:ordinal&gt;&)~"
    R"~(lt;res protocolInfo=&quot;x:*:*:*&quot;&gt;x-rincon-cpcontainer:1004206cspotify%3aalbum%3a00000000000000000000)~"
    R"~(00?sid=9&amp;amp;flags=8300&amp;amp;sn=2&lt;/res&gt;&lt;upnp:albumArtURI&gt;https://i.scdn.co/image/ab67616d00)~"
    R"~(00b273bbbb&lt;/upnp:albumArtURI&gt;&lt;r:type&gt;instantPlay&lt;/r:type&gt;&lt;r:description&gt;Spotify-Album&)~"
    R"~(lt;/r:description&gt;&lt;r:resMD&gt;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;)~"
    R"~(quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rin)~"
    R"~(connetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;)~"
    R"~(&amp;gt;&amp;lt;item id=&amp;quot;1004206cspotify%3aalbum%3a0000000000000000000000&amp;quot; parentID=&amp;quo)~"
    R"~(t;-1&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;dc:title&amp;gt;Stank Face&amp;lt;/dc:title&)~"
    R"~(amp;gt;&amp;lt;upnp:class&amp;gt;object.container.album.musicAlbum&amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&)~"
    R"~(amp;quot;cdudn&amp;quot; nameSpace=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;SA_)~"
    R"~(RINCON2311_X_#Svc2311-0-Token&amp;lt;/desc&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&lt;/r:resMD&)~"
    R"~(gt;&lt;/item&gt;&lt;item id=&quot;FV:2/13&quot; parentID=&quot;FV:2&quot; restricted=&quot;false&quot;&gt;&lt;)~"
    R"~(dc:title&gt;Stayin&amp;apos; Alive&lt;/dc:title&gt;&lt;upnp:class&gt;object.itemobject.item.sonos-favorite&lt;)~"
    R"~(/upnp:class&gt;&lt;r:ordinal&gt;3&lt;/r:ordinal&gt;&lt;res protocolInfo=&quot;x:*:*:*&quot;&gt;x-sonos-spotify)~"
    R"~(:spotify%3atrack%3a1111111111111111111111?sid=9&amp;amp;flags=8224&amp;amp;sn=2&lt;/res&gt;&lt;upnp:albumArtUR)~"
    R"~(I&gt;https://i.scdn.co/image/ab67616d0000b273cccc&lt;/upnp:albumArtURI&gt;&lt;r:type&gt;instantPlay&lt;/r:type)~"
    R"~(&gt;&lt;r:description&gt;Spotify-Titel&lt;/r:description&gt;&lt;r:resMD&gt;&amp;lt;DIDL-Lite xmlns:dc=&amp;quo)~"
    R"~(t;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;)~"
    R"~(quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upn)~"
    R"~(p-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;10032020spotify%3atrack%3a11111111111)~"
    R"~(11111111111&amp;quot; parentID=&amp;quot;-1&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;dc:ti)~"
    R"~(tle&amp;gt;Stayin&amp;amp;apos; Alive&amp;lt;/dc:title&amp;gt;&amp;lt;upnp:class&amp;gt;object.item.audioItem.)~"
    R"~(musicTrack&amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&amp;quot;cdudn&amp;quot; nameSpace=&amp;quot;urn:schemas)~"
    R"~(-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;SA_RINCON2311_X_#Svc2311-0-Token&amp;lt;/desc&amp;gt;&amp;l)~"
    R"~(t;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&lt;/r:resMD&gt;&lt;/item&gt;&lt;item id=&quot;FV:2/14&quot; parentID)~"
    R"~(=&quot;FV:2&quot; restricted=&quot;false&quot;&gt;&lt;dc:title&gt;Sonntagsfrühstück&lt;/dc:title&gt;&lt;upnp:c)~"
    R"~(lass&gt;object.itemobject.item.sonos-favorite&lt;/upnp:class&gt;&lt;r:ordinal&gt;4&lt;/r:ordinal&gt;&lt;res pr)~"
    R"~(otocolInfo=&quot;x:*:*:*&quot;&gt;file:///jffs/settings/savedqueues.rsq#3&lt;/res&gt;&lt;upnp:albumArtURI&gt;/)~"
    R"~(getaa?u=x-rincon-playlist&amp;amp;v=1&lt;/upnp:albumArtURI&gt;&lt;r:type&gt;instantPlay&lt;/r:type&gt;&lt;r:de)~"
    R"~(scription&gt;Sonos-Playlist&lt;/r:description&gt;&lt;r:resMD&gt;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://pu)~"
    R"~(rl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns)~"
    R"~(:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metad)~"
    R"~(ata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;SQ:3&amp;quot; parentID=&amp;quot;-1&amp;quot; r)~"
    R"~(estricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;dc:title&amp;gt;Sonntagsfrühstück&amp;lt;/dc:title&amp;gt;&a)~"
    R"~(mp;lt;upnp:class&amp;gt;object.container.playlistContainer&amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&amp;quot)~"
    R"~(;cdudn&amp;quot; nameSpace=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;RINCON_Asso)~"
    R"~(ciatedZPUDN&amp;lt;/desc&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&lt;/r:resMD&gt;&lt;/item&gt;&l)~"
    R"~(t;item id=&quot;FV:2/15&quot; parentID=&quot;FV:2&quot; restricted=&quot;false&quot;&gt;&lt;dc:title&gt;Sonos )~"
    R"~(Radio Hits&lt;/dc:title&gt;&lt;upnp:class&gt;object.itemobject.item.sonos-favorite&lt;/upnp:class&gt;&lt;r:ord)~"
    R"~(inal&gt;5&lt;/r:ordinal&gt;&lt;res protocolInfo=&quot;x:*:*:*&quot;&gt;x-sonosapi-radio:sonos%3a45?sid=303&amp)~"
    R"~(;amp;flags=8296&amp;amp;sn=9&lt;/res&gt;&lt;upnp:albumArtURI&gt;https://example.com/station.jpg&lt;/upnp:album)~"
    R"~(ArtURI&gt;&lt;r:type&gt;instantPlay&lt;/r:type&gt;&lt;r:description&gt;Sonos Radio&lt;/r:description&gt;&lt;r:)~"
    R"~(resMD&gt;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;)~"
    R"~(urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-)~"
    R"~(0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&am)~"
    R"~(p;quot;100c206csonos%3a45&amp;quot; parentID=&amp;quot;-1&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt)~"
    R"~(;&amp;lt;dc:title&amp;gt;Sonos Radio Hits&amp;lt;/dc:title&amp;gt;&amp;lt;upnp:class&amp;gt;object.item.audioI)~"
    R"~(tem.audioBroadcast.#station&amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&amp;quot;cdudn&amp;quot; nameSpace=&amp)~"
    R"~(;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;SA_RINCON77575_&amp;lt;/desc&amp;gt;&amp;l)~"
    R"~(t;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&lt;/r:resMD&gt;&lt;/item&gt;&lt;item id=&quot;FV:2/16&quot; parentID)~"
    R"~(=&quot;FV:2&quot; restricted=&quot;false&quot;&gt;&lt;dc:title&gt;Nur eine Verknüpfung&lt;/dc:title&gt;&lt;upn)~"
    R"~(p:class&gt;object.itemobject.item.sonos-favorite&lt;/upnp:class&gt;&lt;r:ordinal&gt;6&lt;/r:ordinal&gt;&lt;r:t)~"
    R"~(ype&gt;shortcut&lt;/r:type&gt;&lt;r:description&gt;&lt;/r:description&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;</Resu)~"
    R"~(lt><NumberReturned>7</NumberReturned><TotalMatches>7</TotalMatches><UpdateID>7</UpdateID></u:BrowseResponse></)~"
    R"~(s:Body></s:Envelope>)~";

static const char* kFavoritesEmpty =
    R"~(<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/so)~"
    R"~(ap/encoding/"><s:Body><u:BrowseResponse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><Result>&lt;)~"
    R"~(DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata)~"
    R"~(-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp)~"
    R"~(-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;/DIDL-Lite&gt;</Result><NumberReturned>0</NumberReturned><TotalMatch)~"
    R"~(es>0</TotalMatches><UpdateID>1</UpdateID></u:BrowseResponse></s:Body></s:Envelope>)~";

// Echte Aufzeichnung (Schritt 7, S2): TuneIn-Sender, Amazon-Music-Titel (hls-static),
// Spotify-Titel, Pocket-Casts-Verknüpfung („In Progress“, ohne Adresse), Spotify-Playlist.
// Anonymisiert: ID des persönlichen Spotify-Mix (Elternordner des Titels) durch Nullen ersetzt.
// Die Dienst-Kennungen (SA_RINCON…_X_#Svc…-0-Token) sind Platzhalter von Sonos, keine Geheimnisse.
static const char* kFavoritesRecorded =
    R"~(<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/so)~"
    R"~(ap/encoding/"><s:Body><u:BrowseResponse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><Result>&lt;)~"
    R"~(DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata)~"
    R"~(-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp)~"
    R"~(-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;FV:2/1&quot; parentID=&quot;FV:2&quot; restricted=&quo)~"
    R"~(t;false&quot;&gt;&lt;dc:title&gt;Deutschlandfunk 91.3 (Nationale Nachrichten)&lt;/dc:title&gt;&lt;upnp:class&g)~"
    R"~(t;object.itemobject.item.sonos-favorite&lt;/upnp:class&gt;&lt;r:ordinal&gt;0&lt;/r:ordinal&gt;&lt;res protocol)~"
    R"~(Info=&quot;x-sonosapi-stream:*:*:*&quot;&gt;x-sonosapi-stream:s55737?sid=333&amp;amp;flags=8224&amp;amp;sn=11&)~"
    R"~(lt;/res&gt;&lt;upnp:albumArtURI&gt;http://cdn-profiles.tunein.com/s42828/images/logoq.png?t=1&lt;/upnp:albumAr)~"
    R"~(tURI&gt;&lt;r:type&gt;instantPlay&lt;/r:type&gt;&lt;r:description&gt;TuneIn Sender&lt;/r:description&gt;&lt;r:)~"
    R"~(resMD&gt;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;)~"
    R"~(urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-)~"
    R"~(0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&am)~"
    R"~(p;quot;10092020s55737&amp;quot; parentID=&amp;quot;L&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp)~"
    R"~(;lt;dc:title&amp;gt;Deutschlandfunk 91.3 (Nationale Nachrichten)&amp;lt;/dc:title&amp;gt;&amp;lt;upnp:class&am)~"
    R"~(p;gt;object.item.audioItem.audioBroadcast&amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&amp;quot;cdudn&amp;quot; )~"
    R"~(nameSpace=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;SA_RINCON85255_X_#Svc85255-0)~"
    R"~(-Token&amp;lt;/desc&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&lt;/r:resMD&gt;&lt;/item&gt;&lt;ite)~"
    R"~(m id=&quot;FV:2/0&quot; parentID=&quot;FV:2&quot; restricted=&quot;false&quot;&gt;&lt;dc:title&gt;Friends Will)~"
    R"~( Be Friends (Remastered 2011)&lt;/dc:title&gt;&lt;upnp:class&gt;object.itemobject.item.sonos-favorite&lt;/upnp)~"
    R"~(:class&gt;&lt;r:ordinal&gt;1&lt;/r:ordinal&gt;&lt;res protocolInfo=&quot;x-sonosapi-hls-static:*:*:*&quot;&gt;)~"
    R"~(x-sonosapi-hls-static:catalog%2ftracks%2fB00556W18I%2f%3fplaylistAsin%3dPPEA5F29B514C84AEA890865323D2C86D4%26p)~"
    R"~(laylistType%3dhawkfirePlaylist?sid=201&amp;amp;flags=0&amp;amp;sn=3&lt;/res&gt;&lt;upnp:albumArtURI&gt;https:/)~"
    R"~(/m.media-amazon.com/images/I/71HbLVZW4VL.jpg&lt;/upnp:albumArtURI&gt;&lt;r:type&gt;instantPlay&lt;/r:type&gt;&)~"
    R"~(lt;r:description&gt;Von Queen&lt;/r:description&gt;&lt;r:resMD&gt;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://)~"
    R"~(purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xml)~"
    R"~(ns:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:met)~"
    R"~(adata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;10030000catalog%2ftracks%2fB00556W18I%2f%3fpla)~"
    R"~(ylistAsin%3dPPEA5F29B514C84AEA890865323D2C86D4%26playlistType%3dhawkfirePlaylist&amp;quot; parentID=&amp;quot;)~"
    R"~(1006206ccatalog%2fplaylists%2fPPEA5F29B514C84AEA890865323D2C86D4%2f%23prime_playlist&amp;quot; restricted=&amp)~"
    R"~(;quot;true&amp;quot;&amp;gt;&amp;lt;dc:title&amp;gt;Friends Will Be Friends (Remastered 2011)&amp;lt;/dc:title)~"
    R"~(&amp;gt;&amp;lt;upnp:class&amp;gt;object.item.audioItem.musicTrack&amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&)~"
    R"~(amp;quot;cdudn&amp;quot; nameSpace=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;SA_)~"
    R"~(RINCON51463_X_#Svc51463-0-Token&amp;lt;/desc&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&lt;/r:resM)~"
    R"~(D&gt;&lt;/item&gt;&lt;item id=&quot;FV:2/4&quot; parentID=&quot;FV:2&quot; restricted=&quot;false&quot;&gt;&lt)~"
    R"~(;dc:title&gt;If I Ain’t Got You&lt;/dc:title&gt;&lt;upnp:class&gt;object.itemobject.item.sonos-favorite&lt;/up)~"
    R"~(np:class&gt;&lt;r:ordinal&gt;2&lt;/r:ordinal&gt;&lt;res protocolInfo=&quot;sonos.com-spotify:*:audio/x-spotify)~"
    R"~(:*&quot;&gt;x-sonos-spotify:spotify%3atrack%3a2pIVtQtYOsSptesL6eTMms?sid=9&amp;amp;flags=8232&amp;amp;sn=2&lt;)~"
    R"~(/res&gt;&lt;upnp:albumArtURI&gt;https://i.scdn.co/image/ab67616d0000b27361960a03dec06479a8c9a8c3&lt;/upnp:albu)~"
    R"~(mArtURI&gt;&lt;r:type&gt;instantPlay&lt;/r:type&gt;&lt;r:description&gt;Von Scary Pockets&lt;/r:description&gt)~"
    R"~(;&lt;r:resMD&gt;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&am)~"
    R"~(p;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-com:meta)~"
    R"~(data-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item)~"
    R"~( id=&amp;quot;10032028spotify%3atrack%3a2pIVtQtYOsSptesL6eTMms&amp;quot; parentID=&amp;quot;0006002cspotify%3a)~"
    R"~(playlist%3a0000000000000000000000&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;dc:title&amp;gt)~"
    R"~(;If I Ain’t Got You&amp;lt;/dc:title&amp;gt;&amp;lt;upnp:class&amp;gt;object.item.audioItem.musicTrack&amp;lt;)~"
    R"~(/upnp:class&amp;gt;&amp;lt;desc id=&amp;quot;cdudn&amp;quot; nameSpace=&amp;quot;urn:schemas-rinconnetworks-co)~"
    R"~(m:metadata-1-0/&amp;quot;&amp;gt;SA_RINCON2311_X_#Svc2311-0-Token&amp;lt;/desc&amp;gt;&amp;lt;/item&amp;gt;&am)~"
    R"~(p;lt;/DIDL-Lite&amp;gt;&lt;/r:resMD&gt;&lt;/item&gt;&lt;item id=&quot;FV:2/3&quot; parentID=&quot;FV:2&quot; r)~"
    R"~(estricted=&quot;false&quot;&gt;&lt;dc:title&gt;In Progress&lt;/dc:title&gt;&lt;upnp:class&gt;object.itemobject)~"
    R"~(.item.sonos-favorite&lt;/upnp:class&gt;&lt;r:ordinal&gt;3&lt;/r:ordinal&gt;&lt;res&gt;&lt;/res&gt;&lt;upnp:alb)~"
    R"~(umArtURI&gt;https://integrations.pocketcasts.com/images/inprogress.png&lt;/upnp:albumArtURI&gt;&lt;r:type&gt;s)~"
    R"~(hortcut&lt;/r:type&gt;&lt;r:description&gt;Aus Pocket Casts&lt;/r:description&gt;&lt;r:resMD&gt;&amp;lt;DIDL-L)~"
    R"~(ite xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:me)~"
    R"~(tadata-1-0/upnp/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp)~"
    R"~(;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;10fe00642&amp;qu)~"
    R"~(ot; parentID=&amp;quot;10fe00642&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;dc:title&amp;gt;)~"
    R"~(In Progress&amp;lt;/dc:title&amp;gt;&amp;lt;upnp:class&amp;gt;object.container&amp;lt;/upnp:class&amp;gt;&amp;)~"
    R"~(lt;desc id=&amp;quot;cdudn&amp;quot; nameSpace=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot)~"
    R"~(;&amp;gt;SA_RINCON59655_X_#Svc59655-0-Token&amp;lt;/desc&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt)~"
    R"~(;&lt;/r:resMD&gt;&lt;/item&gt;&lt;item id=&quot;FV:2/2&quot; parentID=&quot;FV:2&quot; restricted=&quot;false&)~"
    R"~(quot;&gt;&lt;dc:title&gt;Jazz-Funk&lt;/dc:title&gt;&lt;upnp:class&gt;object.itemobject.item.sonos-favorite&lt;)~"
    R"~(/upnp:class&gt;&lt;r:ordinal&gt;4&lt;/r:ordinal&gt;&lt;res protocolInfo=&quot;x-rincon-cpcontainer:*:*:*&quot;)~"
    R"~(&gt;x-rincon-cpcontainer:1006206cspotify%3aplaylist%3a37i9dQZF1DWUb0uBnlJuTi?sid=9&amp;amp;flags=8300&amp;amp;)~"
    R"~(sn=2&lt;/res&gt;&lt;upnp:albumArtURI&gt;https://i.scdn.co/image/ab67706f00000002df67fcfccb274659e2e0518b&lt;/u)~"
    R"~(pnp:albumArtURI&gt;&lt;r:type&gt;instantPlay&lt;/r:type&gt;&lt;r:description&gt;Spotify Playliste&lt;/r:descri)~"
    R"~(ption&gt;&lt;r:resMD&gt;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:)~"
    R"~(upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-)~"
    R"~(com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp)~"
    R"~(;lt;item id=&amp;quot;1006206cspotify%3aplaylist%3a37i9dQZF1DWUb0uBnlJuTi&amp;quot; parentID=&amp;quot;0008002)~"
    R"~(4spotify%3aview%3asection0JQ5DAnM3wGh0gz1MXnu5z&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;d)~"
    R"~(c:title&amp;gt;Jazz-Funk&amp;lt;/dc:title&amp;gt;&amp;lt;upnp:class&amp;gt;object.container.playlistContainer&)~"
    R"~(amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&amp;quot;cdudn&amp;quot; nameSpace=&amp;quot;urn:schemas-rinconnetw)~"
    R"~(orks-com:metadata-1-0/&amp;quot;&amp;gt;SA_RINCON2311_X_#Svc2311-0-Token&amp;lt;/desc&amp;gt;&amp;lt;/item&amp)~"
    R"~(;gt;&amp;lt;/DIDL-Lite&amp;gt;&lt;/r:resMD&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;</Result><NumberReturned>5</Numbe)~"
    R"~(rReturned><TotalMatches>5</TotalMatches><UpdateID>1</UpdateID></u:BrowseResponse></s:Body></s:Envelope>)~";

}  // namespace fixtures
