#pragma once

// Browse-Antwort für die Sonos-Favoriten (ObjectID FV:2).
//
// Nachgebaut nach dem bekannten Aufbau (Result = DIDL-Lite einfach kodiert, darin r:resMD
// nochmals kodiert) – eine echte Aufzeichnung folgt mit „sonos_probe.py … --save … favorites“.
// Enthält je einen Favoriten pro Art:
//   TuneIn-Sender, Spotify-Playlist, Spotify-Album, Spotify-Einzeltitel, Sonos-Playlist,
//   Sonos Radio, eine Verknüpfung ohne Adresse.
// Tokens und IDs sind Platzhalter.

namespace fixtures {

static const char* kFavoritesBrowse =
    R"~(<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/so)~"
    R"~(ap/encoding/"><s:Body><u:BrowseResponse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><Result>&lt;)~"
    R"~(DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata)~"
    R"~(-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp)~"
    R"~(-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;FV:2/10&quot; parentID=&quot;FV:2&quot; restricted=&qu)~"
    R"~(ot;false&quot;&gt;&lt;dc:title&gt;Deutschlandfunk&lt;/dc:title&gt;&lt;upnp:class&gt;object.itemobject.item.son)~"
    R"~(os-favorite&lt;/upnp:class&gt;&lt;r:ordinal&gt;0&lt;/r:ordinal&gt;&lt;res protocolInfo=&quot;x:*:*:*&quot;&gt;)~"
    R"~(x-sonosapi-stream:s42828?sid=254&amp;amp;flags=8224&amp;amp;sn=0&lt;/res&gt;&lt;upnp:albumArtURI&gt;https://cd)~"
    R"~(n-profiles.tunein.com/s42828/images/logoq.png&lt;/upnp:albumArtURI&gt;&lt;r:type&gt;instantPlay&lt;/r:type&gt;)~"
    R"~(&lt;r:description&gt;TuneIn&lt;/r:description&gt;&lt;r:resMD&gt;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://pu)~"
    R"~(rl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns)~"
    R"~(:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metad)~"
    R"~(ata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;F00092020s42828&amp;quot; parentID=&amp;quot;-1&)~"
    R"~(amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;dc:title&amp;gt;Deutschlandfunk&amp;lt;/dc:title&)~"
    R"~(amp;gt;&amp;lt;upnp:class&amp;gt;object.item.audioItem.audioBroadcast&amp;lt;/upnp:class&amp;gt;&amp;lt;desc i)~"
    R"~(d=&amp;quot;cdudn&amp;quot; nameSpace=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;)~"
    R"~(SA_RINCON65031_&amp;lt;/desc&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&lt;/r:resMD&gt;&lt;/item&g)~"
    R"~(t;&lt;item id=&quot;FV:2/11&quot; parentID=&quot;FV:2&quot; restricted=&quot;false&quot;&gt;&lt;dc:title&gt;To)~"
    R"~(day&amp;apos;s Top Hits&lt;/dc:title&gt;&lt;upnp:class&gt;object.itemobject.item.sonos-favorite&lt;/upnp:class)~"
    R"~(&gt;&lt;r:ordinal&gt;1&lt;/r:ordinal&gt;&lt;res protocolInfo=&quot;x:*:*:*&quot;&gt;x-rincon-cpcontainer:10062)~"
    R"~(06cspotify%3aplaylist%3a37i9dQZF1DXcBWIGoYBM5M?sid=9&amp;amp;flags=8300&amp;amp;sn=2&lt;/res&gt;&lt;upnp:album)~"
    R"~(ArtURI&gt;https://i.scdn.co/image/ab67706f00000002aaaa&lt;/upnp:albumArtURI&gt;&lt;r:type&gt;instantPlay&lt;/r)~"
    R"~(:type&gt;&lt;r:description&gt;Spotify-Playlist&lt;/r:description&gt;&lt;r:resMD&gt;&amp;lt;DIDL-Lite xmlns:dc=)~"
    R"~(&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/up)~"
    R"~(np/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:sch)~"
    R"~(emas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;1006206cspotify%3aplaylist%3a)~"
    R"~(37i9dQZF1DXcBWIGoYBM5M&amp;quot; parentID=&amp;quot;-1&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&a)~"
    R"~(mp;lt;dc:title&amp;gt;Today&amp;amp;apos;s Top Hits&amp;lt;/dc:title&amp;gt;&amp;lt;upnp:class&amp;gt;object.c)~"
    R"~(ontainer.playlistContainer&amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&amp;quot;cdudn&amp;quot; nameSpace=&amp;)~"
    R"~(quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;SA_RINCON2311_X_#Svc2311-0-Token&amp;lt;/de)~"
    R"~(sc&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&lt;/r:resMD&gt;&lt;/item&gt;&lt;item id=&quot;FV:2/1)~"
    R"~(2&quot; parentID=&quot;FV:2&quot; restricted=&quot;false&quot;&gt;&lt;dc:title&gt;Stank Face&lt;/dc:title&gt;&)~"
    R"~(lt;upnp:class&gt;object.itemobject.item.sonos-favorite&lt;/upnp:class&gt;&lt;r:ordinal&gt;2&lt;/r:ordinal&gt;&)~"
    R"~(lt;res protocolInfo=&quot;x:*:*:*&quot;&gt;x-rincon-cpcontainer:1004206cspotify%3aalbum%3a00000000000000000000)~"
    R"~(00?sid=9&amp;amp;flags=8300&amp;amp;sn=2&lt;/res&gt;&lt;upnp:albumArtURI&gt;https://i.scdn.co/image/ab67616d00)~"
    R"~(00b273bbbb&lt;/upnp:albumArtURI&gt;&lt;r:type&gt;instantPlay&lt;/r:type&gt;&lt;r:description&gt;Spotify-Album&)~"
    R"~(lt;/r:description&gt;&lt;r:resMD&gt;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;)~"
    R"~(quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rin)~"
    R"~(connetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;)~"
    R"~(&amp;gt;&amp;lt;item id=&amp;quot;1004206cspotify%3aalbum%3a0000000000000000000000&amp;quot; parentID=&amp;quo)~"
    R"~(t;-1&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;dc:title&amp;gt;Stank Face&amp;lt;/dc:title&)~"
    R"~(amp;gt;&amp;lt;upnp:class&amp;gt;object.container.album.musicAlbum&amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&)~"
    R"~(amp;quot;cdudn&amp;quot; nameSpace=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;SA_)~"
    R"~(RINCON2311_X_#Svc2311-0-Token&amp;lt;/desc&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&lt;/r:resMD&)~"
    R"~(gt;&lt;/item&gt;&lt;item id=&quot;FV:2/13&quot; parentID=&quot;FV:2&quot; restricted=&quot;false&quot;&gt;&lt;)~"
    R"~(dc:title&gt;Stayin&amp;apos; Alive&lt;/dc:title&gt;&lt;upnp:class&gt;object.itemobject.item.sonos-favorite&lt;)~"
    R"~(/upnp:class&gt;&lt;r:ordinal&gt;3&lt;/r:ordinal&gt;&lt;res protocolInfo=&quot;x:*:*:*&quot;&gt;x-sonos-spotify)~"
    R"~(:spotify%3atrack%3a1111111111111111111111?sid=9&amp;amp;flags=8224&amp;amp;sn=2&lt;/res&gt;&lt;upnp:albumArtUR)~"
    R"~(I&gt;https://i.scdn.co/image/ab67616d0000b273cccc&lt;/upnp:albumArtURI&gt;&lt;r:type&gt;instantPlay&lt;/r:type)~"
    R"~(&gt;&lt;r:description&gt;Spotify-Titel&lt;/r:description&gt;&lt;r:resMD&gt;&amp;lt;DIDL-Lite xmlns:dc=&amp;quo)~"
    R"~(t;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;)~"
    R"~(quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upn)~"
    R"~(p-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;10032020spotify%3atrack%3a11111111111)~"
    R"~(11111111111&amp;quot; parentID=&amp;quot;-1&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;dc:ti)~"
    R"~(tle&amp;gt;Stayin&amp;amp;apos; Alive&amp;lt;/dc:title&amp;gt;&amp;lt;upnp:class&amp;gt;object.item.audioItem.)~"
    R"~(musicTrack&amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&amp;quot;cdudn&amp;quot; nameSpace=&amp;quot;urn:schemas)~"
    R"~(-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;SA_RINCON2311_X_#Svc2311-0-Token&amp;lt;/desc&amp;gt;&amp;l)~"
    R"~(t;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&lt;/r:resMD&gt;&lt;/item&gt;&lt;item id=&quot;FV:2/14&quot; parentID)~"
    R"~(=&quot;FV:2&quot; restricted=&quot;false&quot;&gt;&lt;dc:title&gt;Sonntagsfrühstück&lt;/dc:title&gt;&lt;upnp:c)~"
    R"~(lass&gt;object.itemobject.item.sonos-favorite&lt;/upnp:class&gt;&lt;r:ordinal&gt;4&lt;/r:ordinal&gt;&lt;res pr)~"
    R"~(otocolInfo=&quot;x:*:*:*&quot;&gt;file:///jffs/settings/savedqueues.rsq#3&lt;/res&gt;&lt;upnp:albumArtURI&gt;/)~"
    R"~(getaa?u=x-rincon-playlist&amp;amp;v=1&lt;/upnp:albumArtURI&gt;&lt;r:type&gt;instantPlay&lt;/r:type&gt;&lt;r:de)~"
    R"~(scription&gt;Sonos-Playlist&lt;/r:description&gt;&lt;r:resMD&gt;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://pu)~"
    R"~(rl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns)~"
    R"~(:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metad)~"
    R"~(ata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;SQ:3&amp;quot; parentID=&amp;quot;-1&amp;quot; r)~"
    R"~(estricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;dc:title&amp;gt;Sonntagsfrühstück&amp;lt;/dc:title&amp;gt;&a)~"
    R"~(mp;lt;upnp:class&amp;gt;object.container.playlistContainer&amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&amp;quot)~"
    R"~(;cdudn&amp;quot; nameSpace=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;RINCON_Asso)~"
    R"~(ciatedZPUDN&amp;lt;/desc&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&lt;/r:resMD&gt;&lt;/item&gt;&l)~"
    R"~(t;item id=&quot;FV:2/15&quot; parentID=&quot;FV:2&quot; restricted=&quot;false&quot;&gt;&lt;dc:title&gt;Sonos )~"
    R"~(Radio Hits&lt;/dc:title&gt;&lt;upnp:class&gt;object.itemobject.item.sonos-favorite&lt;/upnp:class&gt;&lt;r:ord)~"
    R"~(inal&gt;5&lt;/r:ordinal&gt;&lt;res protocolInfo=&quot;x:*:*:*&quot;&gt;x-sonosapi-radio:sonos%3a45?sid=303&amp)~"
    R"~(;amp;flags=8296&amp;amp;sn=9&lt;/res&gt;&lt;upnp:albumArtURI&gt;https://example.com/station.jpg&lt;/upnp:album)~"
    R"~(ArtURI&gt;&lt;r:type&gt;instantPlay&lt;/r:type&gt;&lt;r:description&gt;Sonos Radio&lt;/r:description&gt;&lt;r:)~"
    R"~(resMD&gt;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;)~"
    R"~(urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-)~"
    R"~(0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&am)~"
    R"~(p;quot;100c206csonos%3a45&amp;quot; parentID=&amp;quot;-1&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt)~"
    R"~(;&amp;lt;dc:title&amp;gt;Sonos Radio Hits&amp;lt;/dc:title&amp;gt;&amp;lt;upnp:class&amp;gt;object.item.audioI)~"
    R"~(tem.audioBroadcast.#station&amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&amp;quot;cdudn&amp;quot; nameSpace=&amp)~"
    R"~(;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;SA_RINCON77575_&amp;lt;/desc&amp;gt;&amp;l)~"
    R"~(t;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&lt;/r:resMD&gt;&lt;/item&gt;&lt;item id=&quot;FV:2/16&quot; parentID)~"
    R"~(=&quot;FV:2&quot; restricted=&quot;false&quot;&gt;&lt;dc:title&gt;Nur eine Verknüpfung&lt;/dc:title&gt;&lt;upn)~"
    R"~(p:class&gt;object.itemobject.item.sonos-favorite&lt;/upnp:class&gt;&lt;r:ordinal&gt;6&lt;/r:ordinal&gt;&lt;r:t)~"
    R"~(ype&gt;shortcut&lt;/r:type&gt;&lt;r:description&gt;&lt;/r:description&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;</Resu)~"
    R"~(lt><NumberReturned>7</NumberReturned><TotalMatches>7</TotalMatches><UpdateID>7</UpdateID></u:BrowseResponse></)~"
    R"~(s:Body></s:Envelope>)~";

static const char* kFavoritesEmpty =
    R"~(<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/so)~"
    R"~(ap/encoding/"><s:Body><u:BrowseResponse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><Result>&lt;)~"
    R"~(DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata)~"
    R"~(-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp)~"
    R"~(-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;/DIDL-Lite&gt;</Result><NumberReturned>0</NumberReturned><TotalMatch)~"
    R"~(es>0</TotalMatches><UpdateID>1</UpdateID></u:BrowseResponse></s:Body></s:Envelope>)~";

}  // namespace fixtures
